name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run tests
      run: go test ./... -v
    
    - name: Build binaries
      run: |
        mkdir -p dist
        # Windows
        GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${GITHUB_REF#refs/tags/}" -o dist/markdowner-windows-amd64.exe .
        # Linux
        GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${GITHUB_REF#refs/tags/}" -o dist/markdowner-linux-amd64 .
        # macOS Intel
        GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${GITHUB_REF#refs/tags/}" -o dist/markdowner-darwin-amd64 .
        # macOS Apple Silicon
        GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${GITHUB_REF#refs/tags/}" -o dist/markdowner-darwin-arm64 .
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/markdowner-windows-amd64.exe
          dist/markdowner-linux-amd64
          dist/markdowner-darwin-amd64
          dist/markdowner-darwin-arm64
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}